# Generated by Django 4.2.25 on 2025-10-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_date_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
